stages:
  - v3Dev
  - master
  - sonarqube-check

variables:
  GIT_CLEAN_FLAGS: none

master:
  stage: master
  only:
    - master
  tags:
    - zjjhq
  script:
    - if [ ! -d "/home/wwwroot/$CI_PROJECT_NAME" ];then ln -s $CI_PROJECT_DIR /home/wwwroot; echo "目录已创建！"; else echo "目录已存在！";fi
  environment:
    name: production
  when: manual

develop:
  stage: v3Dev
  tags:
    - golive-test
  only:
    - v3Dev
  script:
    - if [ ! -d "/home/wwwroot/$CI_PROJECT_NAME" ];then ln -s $CI_PROJECT_DIR /home/wwwroot; echo "目录已创建！"; else echo "目录已存在！";fi

sonarqube-check:
  stage: sonarqube-check
  tags:
    - sonarqube-check
  script: 
    - sonar-scanner -Dsonar.projectKey=zjtie_zjtie_activitysupport_wap_AYv_8yoy3Iv7fQhy85gF
  allow_failure: true
  only:
    - v3Dev