stages:
  - master
  - develop

variables:
  GIT_CLEAN_FLAGS: none

master:
  stage: master
  only:
    - master
  tags:
    - golive-35
  script:
    - if [ ! -d "/home/wwwroot/$CI_PROJECT_NAME" ];then ln -s $CI_PROJECT_DIR /home/wwwroot; echo "目录已创建！"; else echo "目录已存在！";fi
  environment:
    name: production
  when: manual

develop:
  stage: develop
  tags:
    - golive-test
  only:
    - develop
  script:
    - if [ ! -d "/home/wwwroot/$CI_PROJECT_NAME" ];then ln -s $CI_PROJECT_DIR /home/wwwroot; echo "目录已创建！"; else echo "目录已存在！";fi