/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    NutButton: typeof import('@nutui/nutui')['Button']
    NutCellGroup: typeof import('@nutui/nutui')['CellGroup']
    NutDatePicker: typeof import('@nutui/nutui')['DatePicker']
    NutField: typeof import('@nutui/nutui')['Field']
    NutForm: typeof import('@nutui/nutui')['Form']
    NutPopup: typeof import('@nutui/nutui')['Popup']
    NutUploader: typeof import('@nutui/nutui')['Uploader']
    VanButton: typeof import('vant/es')['Button']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanDatetimePicker: typeof import('vant/es')['DatetimePicker']
    VanField: typeof import('vant/es')['Field']
    VanForm: typeof import('vant/es')['Form']
    VanLoading: typeof import('vant/es')['Loading']
    VanOverlay: typeof import('vant/es')['Overlay']
    VanPicker: typeof import('vant/es')['Picker']
    VanPopup: typeof import('vant/es')['Popup']
    VanUploader: typeof import('vant/es')['Uploader']
  }
}
