export const listJosn = {
  code: 200,
  msg: '成功',
  data: {
    id: 539,
    tenant_id: 233,
    tenant_code: 'H10172',
    department_list: null,
    cancel_department_list: null,
    username: '155****7071',
    name: '昼',
    phone: '',
    avatar: '',
    role_id: 0,
    status: 1,
    super: 1,
    is_permission: 1,
    parent_id: 539,
    tenant_logo: 'https://golivecc-huadong1.oss-cn-hangzhou.aliyuncs.com/laravel/dcfab15a64e011ee9946d09466665459.png',
    tenant_name: '昼',
    bottom_copy: null,
    is_forced_card: 2,
    is_workbench: 2,
    service_hall_link: 'https://H10172-wap-dev.goliveplus.cn',
    saas_pc: 'https://dev-saas.goliveplus.cn/home',
    is_use_new_onecode: 2,
    is_gcard: 2,
    is_user_face: 2,
    menu_list: [
      {
        type_id: 14,
        type_name: '模块名称',
        en_name: 'moduleName',
        sort: 49.678236246106,
        total: 2,
        child: [
          {
            id: 24,
            type_id: 14,
            name: '应用名称',
            en_name: 'applicationName',
            identification: 'applicationName',
            is_external: 2,
            external_url: 'https://dev-saas-wisdom-restaurant.goliveplus.cn',
            logo: 'https://golivecc-huadong1.oss-cn-hangzhou.aliyuncs.com/gp/eb29e686414911eca6eb00163e14b2cc.png',
            version: 'v1.1.1',
            sort: 32968.75,
            list: [
              {
                id: 92,
                pid: 0,
                name: '应用首页',
                en_name: 'OrderFoodIndex',
                is_nav: 2,
                router: 'api/saas/admin/order-food/index',
                level: 1,
                sort: 2578.125,
                features: [
                  {
                    id: 93,
                    pid: 92,
                    name: '订单笔数金额',
                    en_name: 'OrderFoodOrderRough',
                    is_nav: 2,
                    router: 'api/saas/admin/order-food/adminPage/orderRough',
                    level: 3,
                    sort: 10000,
                  },
                  {
                    id: 94,
                    pid: 92,
                    name: '科室订单对比',
                    en_name: 'OrderFoodDepartmentOrderCompared',
                    is_nav: 2,
                    router: 'api/saas/admin/order-food/adminPage/departmentOrderCompared',
                    level: 3,
                    sort: 20000,
                  },
                  {
                    id: 95,
                    pid: 92,
                    name: '应用订单',
                    en_name: 'OrderFoodOrderDescWithTime',
                    is_nav: 2,
                    router: 'api/saas/admin/order-food/adminPage/orderDescWithTime',
                    level: 3,
                    sort: 30000,
                  },
                  {
                    id: 96,
                    pid: 92,
                    name: '菜品销售排行',
                    en_name: 'OrderFoodOrderFoodWithTime',
                    is_nav: 2,
                    router: 'api/saas/admin/order-food/adminPage/orderFoodWithTime',
                    level: 3,
                    sort: 40000,
                  },
                ],
              },
              {
                id: 624,
                pid: 0,
                name: '表单表格',
                en_name: 'CommentsManagement',
                is_nav: 2,
                router: 'api/saas/admin/order-food/order_evaluate/getList',
                level: 1,
                sort: 2900.390625,
              },
              {
                id: 105,
                pid: 0,
                name: '影像模块',
                en_name: 'OrdeFoodFinancialStatements',
                is_nav: 1,
                router: null,
                level: 1,
                sort: 3222.65625,
                child: [
                  {
                    id: 106,
                    pid: 105,
                    name: '视频内容',
                    en_name: 'OrderFoodBusinessSummary',
                    is_nav: 2,
                    router: 'http://fine.report.goliveplus.cn:38888/socket.io/',
                    level: 2,
                    sort: 22500,
                    features: [
                      {
                        id: 696,
                        pid: 106,
                        name: '导出Excel',
                        en_name: 'export',
                        is_nav: 2,
                        router: 'api/saas/admin/order-food/finance/getBusinessStatementExcel',
                        level: 3,
                        sort: 10000,
                      },
                    ],
                  },
                  {
                    id: 1657,
                    pid: 105,
                    name: '图片内容',
                    en_name: 'reconciliation',
                    is_nav: 2,
                    router: 'api/saas/admin/order-food/finance/getTransactionFlow',
                    level: 2,
                    sort: 25625,
                  },
                  {
                    id: 157,
                    pid: 105,
                    name: '音频内容',
                    en_name: 'OrderFoodSalesStatistics',
                    is_nav: 2,
                    router: 'api/saas/admin/order-food/finance/getSalesStatistics',
                    level: 2,
                    sort: 27500,
                  },
                  {
                    id: 1484,
                    pid: 105,
                    name: '通讯内容',
                    en_name: 'singleSourceStatistics',
                    is_nav: 2,
                    router: 'api/saas/admin/order-food/finance/getSourceStatement',
                    level: 2,
                    sort: 30000,
                  },
                ],
              },
              {
                id: 89,
                pid: 0,
                name: '其他管理',
                en_name: 'OrderFoodOrderManager',
                is_nav: 2,
                router: 'api/saas/admin/order-food/order/list',
                level: 1,
                sort: 3867.1875,
                features: [
                  {
                    id: 97,
                    pid: 89,
                    name: '详情',
                    en_name: 'OrderFoodOrderInfo',
                    is_nav: 2,
                    router: 'api/saas/admin/order-food/order/info',
                    level: 3,
                    sort: 20000,
                  },
                  {
                    id: 98,
                    pid: 89,
                    name: '导出',
                    en_name: 'OrderFoodExport',
                    is_nav: 2,
                    router: 'api/saas/admin/order-food/order/export',
                    level: 3,
                    sort: 30000,
                  },
                  {
                    id: 99,
                    pid: 89,
                    name: '统计打印订单',
                    en_name: 'OrderFoodPrintForStaff',
                    is_nav: 2,
                    router: 'api/saas/admin/order-food/order/printForStaff',
                    level: 3,
                    sort: 40000,
                  },
                  {
                    id: 100,
                    pid: 89,
                    name: '详细打印订单',
                    en_name: 'OrderFoodPrintForUser',
                    is_nav: 2,
                    router: 'api/saas/admin/order-food/order/printForUser',
                    level: 3,
                    sort: 50000,
                  },
                  {
                    id: 101,
                    pid: 89,
                    name: '科室打印订单',
                    en_name: 'OrderFoodPrintByDepartment',
                    is_nav: 2,
                    router: 'api/saas/admin/order-food/order/printByDepartment',
                    level: 3,
                    sort: 60000,
                  },
                  {
                    id: 102,
                    pid: 89,
                    name: '获取下单科室',
                    en_name: 'OrderFoodGetDepartmentByOrder',
                    is_nav: 2,
                    router: 'api/saas/admin/order-food/order/getDepartmentByOrder',
                    level: 3,
                    sort: 70000,
                  },
                  {
                    id: 147,
                    pid: 89,
                    name: '签收',
                    en_name: 'Signing',
                    is_nav: 2,
                    router: 'api/saas/admin/order-food/food-Signing',
                    level: 3,
                    sort: 80000,
                  },
                  {
                    id: 148,
                    pid: 89,
                    name: '审核',
                    en_name: 'Review',
                    is_nav: 2,
                    router: 'api/saas/admin/order-food/food-Review',
                    level: 3,
                    sort: 90000,
                  },
                  {
                    id: 472,
                    pid: 89,
                    name: '配送打印订单',
                    en_name: 'printByBuild',
                    is_nav: 2,
                    router: 'api/saas/admin/order-food/order/printByBuild',
                    level: 3,
                    sort: 100000,
                  },
                  {
                    id: 512,
                    pid: 89,
                    name: '小票批量打印',
                    en_name: 'batchPrinting',
                    is_nav: 2,
                    router: 'api/saas/admin/order-food/order/printOrder',
                    level: 3,
                    sort: 110000,
                  },
                  {
                    id: 513,
                    pid: 89,
                    name: '小票一键打印',
                    en_name: 'oneClickPrinting',
                    is_nav: 2,
                    router: 'api/saas/admin/order-food/order/printAllOrder',
                    level: 3,
                    sort: 120000,
                  },
                  {
                    id: 658,
                    pid: 89,
                    name: '自取订单打印',
                    en_name: 'pickUpOrder',
                    is_nav: 2,
                    router: 'api/saas/admin/order-food/order/printBySelfDelivery',
                    level: 3,
                    sort: 130000,
                  },
                  {
                    id: 685,
                    pid: 89,
                    name: '订单退款',
                    en_name: 'reimburse',
                    is_nav: 2,
                    router: 'api/saas/admin/order-food/order/refund',
                    level: 3,
                    sort: 140000,
                  },
                  {
                    id: 690,
                    pid: 89,
                    name: '标签打印',
                    en_name: 'printOrder',
                    is_nav: 2,
                    router: 'api/saas/admin/order-food/order/printOrderFood',
                    level: 3,
                    sort: 150000,
                  },
                  {
                    id: 695,
                    pid: 89,
                    name: '楼幢订单打印',
                    en_name: 'buildingOrders',
                    is_nav: 2,
                    router: 'api/saas/admin/order-food/order/printByBuild_tl',
                    level: 3,
                    sort: 160000,
                  },
                  {
                    id: 1384,
                    pid: 89,
                    name: '病区配送打印',
                    en_name: 'PrintingofwardDistributionReport',
                    is_nav: 2,
                    router: 'api/saas/admin/oreder-food/printingofward',
                    level: 3,
                    sort: 170000,
                  },
                  {
                    id: 1466,
                    pid: 89,
                    name: '病区营养餐打印',
                    en_name: 'wardNutritiousMealPrinting',
                    is_nav: 2,
                    router: 'api/saas/admin/order-food/order/printPatientListForHN',
                    level: 3,
                    sort: 180000,
                  },
                  {
                    id: 1522,
                    pid: 89,
                    name: '部门标签打印',
                    en_name: 'departmentLabelPrinting',
                    is_nav: 2,
                    router: 'api/saas/admin/order-food/order/printFoodsByDepartment',
                    level: 3,
                    sort: 190000,
                  },
                  {
                    id: 1923,
                    pid: 89,
                    name: '打印异常',
                    en_name: 'getPrintLog',
                    is_nav: 2,
                    router: 'api/saas/admin/order-food/order/getPrintLog',
                    level: 3,
                    sort: 210000,
                  },
                ],
              },
              {
                id: 107,
                pid: 0,
                name: '设置内容',
                en_name: 'OrderFoodSupplyManagement',
                is_nav: 1,
                router: null,
                level: 1,
                sort: 30000,
                child: [
                  {
                    id: 108,
                    pid: 107,
                    name: '库管理',
                    en_name: 'OrderFoodRepositoryManage',
                    is_nav: 2,
                    router: 'api/saas/admin/order-food/food-repository/list',
                    level: 2,
                    sort: 10000,
                    features: [
                      {
                        id: 114,
                        pid: 108,
                        name: '新增',
                        en_name: 'OrderFoodRepositoryAdd',
                        is_nav: 2,
                        router: 'api/saas/admin/order-food/food-repository/add',
                        level: 3,
                        sort: 10000,
                      },
                      {
                        id: 115,
                        pid: 108,
                        name: '上架菜品',
                        en_name: 'OrderFoodRepositoryUpper',
                        is_nav: 2,
                        router: 'api/saas/admin/order-food/food-repository/batchUpper',
                        level: 3,
                        sort: 20000,
                      },
                      {
                        id: 116,
                        pid: 108,
                        name: '下架菜品',
                        en_name: 'OrderFoodRepositoryLower',
                        is_nav: 2,
                        router: 'api/saas/admin/order-food/food-repository/batchLower',
                        level: 3,
                        sort: 30000,
                      },
                      {
                        id: 117,
                        pid: 108,
                        name: '编辑菜品',
                        en_name: 'OrderFoodRepositoryEdit',
                        is_nav: 2,
                        router: 'api/saas/admin/order-food/food-repository/edit',
                        level: 3,
                        sort: 40000,
                      },
                      {
                        id: 118,
                        pid: 108,
                        name: '详情',
                        en_name: 'OrderFoodRepositoryInfo',
                        is_nav: 2,
                        router: 'api/saas/admin/order-food/food-repository/info',
                        level: 3,
                        sort: 50000,
                      },
                      {
                        id: 119,
                        pid: 108,
                        name: '删除',
                        en_name: 'OrderFoodRepositoryDel',
                        is_nav: 2,
                        router: 'api/saas/admin/order-food/food-repository/delete',
                        level: 3,
                        sort: 60000,
                      },
                      {
                        id: 514,
                        pid: 108,
                        name: '菜品导入',
                        en_name: 'FoodImport',
                        is_nav: 2,
                        router: 'api/saas/admin/order-food/food-repository/import',
                        level: 3,
                        sort: 70000,
                      },
                      {
                        id: 515,
                        pid: 108,
                        name: '菜品图片导入',
                        en_name: 'ImportOfDishPictures',
                        is_nav: 2,
                        router: 'api/saas/admin/order-food/public/ossUpload',
                        level: 3,
                        sort: 80000,
                      },
                      {
                        id: 516,
                        pid: 108,
                        name: '下载模板',
                        en_name: 'DownloadTheTemplate',
                        is_nav: 2,
                        router: 'api/saas/admin/order-food/food-repository/export_template',
                        level: 3,
                        sort: 90000,
                      },
                      {
                        id: 1518,
                        pid: 108,
                        name: '批量删除',
                        en_name: 'bulkDeletion',
                        is_nav: 2,
                        router: 'api/saas/admin/order-food/food-repository/batchDelete',
                        level: 3,
                        sort: 100000,
                      },
                      {
                        id: 1914,
                        pid: 108,
                        name: '图片库文件夹',
                        en_name: 'listImageFile',
                        is_nav: 2,
                        router: 'api/saas/admin/order-food/food-repository/listImageFile',
                        level: 3,
                        sort: 110000,
                      },
                      {
                        id: 1915,
                        pid: 108,
                        name: '文件夹图片',
                        en_name: 'getImageFilePicList',
                        is_nav: 2,
                        router: 'api/saas/admin/order-food/food-repository/getImageFilePicList',
                        level: 3,
                        sort: 120000,
                      },
                      {
                        id: 1917,
                        pid: 108,
                        name: '同步至商品',
                        en_name: 'coverImageFood',
                        is_nav: 2,
                        router: 'api/saas/admin/order-food/food-repository/coverImageFood',
                        level: 3,
                        sort: 130000,
                      },
                      {
                        id: 1918,
                        pid: 108,
                        name: '导入记录',
                        en_name: 'importLogList',
                        is_nav: 2,
                        router: 'api/saas/admin/order-food/food-repository/importLogList',
                        level: 3,
                        sort: 140000,
                      },
                      {
                        id: 1919,
                        pid: 108,
                        name: '新增文件夹',
                        en_name: 'addImageFile',
                        is_nav: 2,
                        router: 'api/saas/admin/order-food/food-repository/addImageFile',
                        level: 3,
                        sort: 150000,
                      },
                      {
                        id: 1920,
                        pid: 108,
                        name: '编辑文件夹',
                        en_name: 'editImageFile',
                        is_nav: 2,
                        router: 'api/saas/admin/order-food/food-repository/editImageFile',
                        level: 3,
                        sort: 160000,
                      },
                      {
                        id: 1921,
                        pid: 108,
                        name: '删除文件夹',
                        en_name: 'delImageFile',
                        is_nav: 2,
                        router: 'api/saas/admin/order-food/food-repository/delImageFile',
                        level: 3,
                        sort: 170000,
                      },
                      {
                        id: 1922,
                        pid: 108,
                        name: '删除文件夹图片',
                        en_name: 'delImageFilePic',
                        is_nav: 2,
                        router: 'api/saas/admin/order-food/food-repository/delImageFilePic',
                        level: 3,
                        sort: 180000,
                      },
                    ],
                  },
                  {
                    id: 110,
                    pid: 107,
                    name: '区域管理',
                    en_name: 'OrderFoodCanteenManage',
                    is_nav: 2,
                    router: 'api/saas/admin/order-food/canteen/list',
                    level: 2,
                    sort: 20000,
                    features: [
                      {
                        id: 120,
                        pid: 110,
                        name: '新增食堂',
                        en_name: 'OrdeFoodCanteenAdd',
                        is_nav: 2,
                        router: 'api/saas/admin/order-food/canteen/add',
                        level: 3,
                        sort: 10000,
                      },
                      {
                        id: 121,
                        pid: 110,
                        name: '食堂详情',
                        en_name: 'OrderFoodCanteenInfo',
                        is_nav: 2,
                        router: 'api/saas/admin/order-food/canteen/info',
                        level: 3,
                        sort: 20000,
                      },
                      {
                        id: 122,
                        pid: 110,
                        name: '食堂编辑',
                        en_name: 'OrderFoodCanteenEdit',
                        is_nav: 2,
                        router: 'api/saas/admin/order-food/canteen/edit',
                        level: 3,
                        sort: 30000,
                      },
                      {
                        id: 123,
                        pid: 110,
                        name: '食堂删除',
                        en_name: 'OrderFoodCanteenDel',
                        is_nav: 2,
                        router: 'api/saas/admin/order-food/canteen/delete',
                        level: 3,
                        sort: 40000,
                      },
                      {
                        id: 124,
                        pid: 110,
                        name: '营业/停业',
                        en_name: 'OrderFoodCanteenTrade',
                        is_nav: 2,
                        router: 'api/saas/admin/order-food/canteen/editStatus',
                        level: 3,
                        sort: 50000,
                      },
                      {
                        id: 125,
                        pid: 110,
                        name: '上架菜品',
                        en_name: 'OrderFoodFoodAdd',
                        is_nav: 2,
                        router: 'api/saas/admin/order-food/food/add',
                        level: 3,
                        sort: 60000,
                      },
                      {
                        id: 171,
                        pid: 110,
                        name: '下架菜品',
                        en_name: 'batchLower',
                        is_nav: 2,
                        router: 'api/saas/admin/order-food/food-repository/batchLower',
                        level: 3,
                        sort: 70000,
                      },
                    ],
                  },
                  {
                    id: 908,
                    pid: 107,
                    name: '内容管理',
                    en_name: 'doctorsAdvice',
                    is_nav: 2,
                    router: 'api/saas/admin/order-food/advice/listadviceManagement',
                    level: 2,
                    sort: 30000,
                  },
                  {
                    id: 1081,
                    pid: 107,
                    name: '人员管理',
                    en_name: 'materialManage',
                    is_nav: 2,
                    router: 'api/saas/admin/order-food/nutrition/material/list',
                    level: 2,
                    sort: 40000,
                    features: [
                      {
                        id: 1082,
                        pid: 1081,
                        name: '新增原料',
                        en_name: 'addMaterial',
                        is_nav: 2,
                        router: 'api/saas/admin/order-food/nutrition/material/add',
                        level: 3,
                        sort: 10000,
                      },
                      {
                        id: 1083,
                        pid: 1081,
                        name: '编辑原料',
                        en_name: 'editMaterial',
                        is_nav: 2,
                        router: 'api/saas/admin/order-food/nutrition/material/edit',
                        level: 3,
                        sort: 20000,
                      },
                      {
                        id: 1084,
                        pid: 1081,
                        name: '新增原料分类',
                        en_name: 'addCategory',
                        is_nav: 2,
                        router: 'api/saas/admin/order-food/nutrition/category/add',
                        level: 3,
                        sort: 30000,
                      },
                      {
                        id: 1085,
                        pid: 1081,
                        name: '新增营养成分',
                        en_name: 'addElement',
                        is_nav: 2,
                        router: 'api/saas/admin/order-food/nutrition/element/add',
                        level: 3,
                        sort: 40000,
                      },
                      {
                        id: 1086,
                        pid: 1081,
                        name: '编辑营养成分',
                        en_name: 'editElement',
                        is_nav: 2,
                        router: 'api/saas/admin/order-food/nutrition/element/edit',
                        level: 3,
                        sort: 50000,
                      },
                    ],
                  },
                ],
              },
              {
                id: 925,
                pid: 0,
                name: '权限管理',
                en_name: 'authorityControl',
                is_nav: 2,
                router: 'account/authorityControl',
                level: 1,
                sort: 41250,
              },
              {
                id: 511,
                pid: 0,
                name: '拓展功能',
                en_name: 'AdditionalFunction',
                is_nav: 1,
                router: null,
                level: 1,
                sort: 42500,
                child: [
                  {
                    id: 564,
                    pid: 511,
                    name: '白名单管理',
                    en_name: 'WhitelistManagement',
                    is_nav: 2,
                    router: 'api/saas/admin/order-food/whiteUser/list',
                    level: 2,
                    sort: 10000,
                    features: [
                      {
                        id: 568,
                        pid: 564,
                        name: '查询',
                        en_name: 'Inquire',
                        is_nav: 2,
                        router: 'Inquirefjkfjfjfjdjd',
                        level: 3,
                        sort: 10000,
                      },
                      {
                        id: 569,
                        pid: 564,
                        name: '新增',
                        en_name: 'Adddevice',
                        is_nav: 2,
                        router: 'Adddevicejjd',
                        level: 3,
                        sort: 20000,
                      },
                      {
                        id: 570,
                        pid: 564,
                        name: '批量导入',
                        en_name: 'Bulkimport',
                        is_nav: 2,
                        router: 'BulkimportBulkimport',
                        level: 3,
                        sort: 30000,
                      },
                      {
                        id: 571,
                        pid: 564,
                        name: '导出模版',
                        en_name: 'ExportThetemplate',
                        is_nav: 2,
                        router: 'ExportThetemplate',
                        level: 3,
                        sort: 40000,
                      },
                      {
                        id: 572,
                        pid: 564,
                        name: '加入黑名单',
                        en_name: 'Jointheblacklist',
                        is_nav: 2,
                        router: 'Jointheblacklist',
                        level: 3,
                        sort: 50000,
                      },
                      {
                        id: 573,
                        pid: 564,
                        name: '移除黑名单',
                        en_name: 'Removeblacklist',
                        is_nav: 2,
                        router: 'Removeblacklist',
                        level: 3,
                        sort: 60000,
                      },
                      {
                        id: 574,
                        pid: 564,
                        name: '编辑',
                        en_name: 'edit',
                        is_nav: 2,
                        router: 'editedit',
                        level: 3,
                        sort: 70000,
                      },
                      {
                        id: 575,
                        pid: 564,
                        name: '删除',
                        en_name: 'delete',
                        is_nav: 2,
                        router: 'deletedelete',
                        level: 3,
                        sort: 80000,
                      },
                    ],
                  },
                  {
                    id: 565,
                    pid: 511,
                    name: '超级AI',
                    en_name: 'SignTheBillManagement',
                    is_nav: 2,
                    router: 'api/saas/admin/order-food/onCredit/group_list',
                    level: 2,
                    sort: 20000,
                    features: [
                      {
                        id: 576,
                        pid: 565,
                        name: '新增',
                        en_name: 'Adddevice',
                        is_nav: 2,
                        router: 'Adddevicejjdjdj',
                        level: 3,
                        sort: 10000,
                      },
                      {
                        id: 577,
                        pid: 565,
                        name: '查询',
                        en_name: 'Inquire',
                        is_nav: 2,
                        router: 'Inquirefjkfjf',
                        level: 3,
                        sort: 20000,
                      },
                      {
                        id: 578,
                        pid: 565,
                        name: '导出',
                        en_name: 'Export',
                        is_nav: 2,
                        router: 'Exportfjfjjfjf',
                        level: 3,
                        sort: 30000,
                      },
                      {
                        id: 579,
                        pid: 565,
                        name: '禁用',
                        en_name: 'Disable',
                        is_nav: 2,
                        router: 'Disablesfjjdj',
                        level: 3,
                        sort: 40000,
                      },
                      {
                        id: 580,
                        pid: 565,
                        name: '编辑',
                        en_name: 'edit',
                        is_nav: 2,
                        router: 'editediteditedit',
                        level: 3,
                        sort: 50000,
                      },
                      {
                        id: 581,
                        pid: 565,
                        name: '明细',
                        en_name: 'Thedetail',
                        is_nav: 2,
                        router: 'ThedetailThedetailThedetail',
                        level: 3,
                        sort: 60000,
                      },
                      {
                        id: 582,
                        pid: 565,
                        name: '删除',
                        en_name: 'delete',
                        is_nav: 2,
                        router: 'deletedeletedelete',
                        level: 3,
                        sort: 70000,
                      },
                      {
                        id: 583,
                        pid: 565,
                        name: '启用',
                        en_name: 'Enable',
                        is_nav: 2,
                        router: 'EnableEnableEnable',
                        level: 3,
                        sort: 80000,
                      },
                    ],
                  },
                  {
                    id: 566,
                    pid: 511,
                    name: '低代码',
                    en_name: 'SignUpusermanagement',
                    is_nav: 2,
                    router: 'api/saas/admin/order-food/onCredit/user_list',
                    level: 2,
                    sort: 30000,
                    features: [
                      {
                        id: 584,
                        pid: 566,
                        name: '新增',
                        en_name: 'Adddevice',
                        is_nav: 2,
                        router: 'AdddeviceAdddevice',
                        level: 3,
                        sort: 10000,
                      },
                      {
                        id: 585,
                        pid: 566,
                        name: '查询',
                        en_name: 'Inquire',
                        is_nav: 2,
                        router: 'InquireInquire',
                        level: 3,
                        sort: 20000,
                      },
                      {
                        id: 586,
                        pid: 566,
                        name: '导出excel',
                        en_name: 'Export',
                        is_nav: 2,
                        router: 'ExportExport',
                        level: 3,
                        sort: 30000,
                      },
                      {
                        id: 587,
                        pid: 566,
                        name: '启用',
                        en_name: 'Enable',
                        is_nav: 2,
                        router: 'EnableEnable',
                        level: 3,
                        sort: 40000,
                      },
                      {
                        id: 588,
                        pid: 566,
                        name: '禁用',
                        en_name: 'Disable',
                        is_nav: 2,
                        router: 'DisableDisable',
                        level: 3,
                        sort: 50000,
                      },
                      {
                        id: 589,
                        pid: 566,
                        name: '编辑',
                        en_name: 'edit',
                        is_nav: 2,
                        router: 'editediteditediteditedit',
                        level: 3,
                        sort: 60000,
                      },
                      {
                        id: 590,
                        pid: 566,
                        name: '明细',
                        en_name: 'Thedetail',
                        is_nav: 2,
                        router: 'ThedetailThedetail',
                        level: 3,
                        sort: 70000,
                      },
                      {
                        id: 591,
                        pid: 566,
                        name: '删除',
                        en_name: 'delete',
                        is_nav: 2,
                        router: 'deletedeletedeletedeletedelete',
                        level: 3,
                        sort: 80000,
                      },
                    ],
                  },
                  {
                    id: 567,
                    pid: 511,
                    name: '视图模块',
                    en_name: 'RestaurantMiddle',
                    is_nav: 2,
                    router: 'RestaurantMiddle',
                    level: 2,
                    sort: 40000,
                    features: [
                      {
                        id: 592,
                        pid: 567,
                        name: '查询',
                        en_name: 'Lnquire',
                        is_nav: 2,
                        router: 'Lnquire',
                        level: 3,
                        sort: 10000,
                      },
                      {
                        id: 593,
                        pid: 567,
                        name: '导出',
                        en_name: 'Export',
                        is_nav: 2,
                        router: 'ExportExportExport',
                        level: 3,
                        sort: 20000,
                      },
                      {
                        id: 594,
                        pid: 567,
                        name: '详情',
                        en_name: 'OrderFoodOrderInfo',
                        is_nav: 2,
                        router: 'OrderFoodOrderInfoOrderFoodOrderInfo',
                        level: 3,
                        sort: 30000,
                      },
                      {
                        id: 595,
                        pid: 567,
                        name: '开票',
                        en_name: 'MakeOutAnInvoic',
                        is_nav: 2,
                        router: 'makeoutaninvoice',
                        level: 3,
                        sort: 40000,
                      },
                    ],
                  },
                  {
                    id: 1088,
                    pid: 511,
                    name: '第三方管理',
                    en_name: 'oyherDataStatistics',
                    is_nav: 2,
                    router: 'api/saas/admin/order-food/other_order/list',
                    level: 2,
                    sort: 50000,
                  },
                ],
              },
            ],
          },
        ],
      },
    ],
    // 可请求接口
    permission_list: [
      'api/saas/user-center/department/get-users-by-department',
      'api/saas/user-center/audit/list',
      'api/saas/user-center/identity/list',
      'api/saas/user-center/department/get-department-list',
      'api/saas/user-center/department/store',
      'api/saas/user-center/department/edit',
      'api/saas/user-center/department/delete',
      'api/saas/user-center/information/add',
      'api/saas/user-center/information/delete',
      'api/saas/user-center/department/export',
      'api/saas/user-center/information/edit',
      'api/saas/user-center/information/update/batch-import',
      'api/saas/user-center/information/delete/batch-import',
      'api/saas/user-center/audit/synchroPhoto',
      'api/saas/user-center/audit/untied',
      'api/saas/user-center/audit/pass',
      'api/saas/user-center/identity/add',
      'api/saas/user-center/identity/edit',
      'api/saas/user-center/identity/delete',
      'api/saas/admin/order-food/order_evaluate/getList',
      'api/saas/admin/order-food/index',
      'http://fine.report.goliveplus.cn:38888/socket.io/',
      'api/saas/admin/order-food/finance/getBusinessStatementExcel',
      'api/saas/admin/order-food/finance/getTransactionFlow',
      'api/saas/admin/order-food/finance/getSalesStatistics',
      'api/saas/admin/order-food/finance/getSourceStatement',
      'api/saas/admin/order-food/order/list',
      'api/saas/admin/order-food/food-repository/list',
      'api/saas/admin/order-food/food-repository/add',
      'api/saas/admin/order-food/food-repository/batchUpper',
      'api/saas/admin/order-food/food-repository/batchLower',
      'api/saas/admin/order-food/food-repository/edit',
      'api/saas/admin/order-food/food-repository/info',
      'api/saas/admin/order-food/food-repository/delete',
      'api/saas/admin/order-food/food-repository/import',
      'api/saas/admin/order-food/public/ossUpload',
      'api/saas/admin/order-food/food-repository/export_template',
      'api/saas/admin/order-food/food-repository/batchDelete',
      'api/saas/admin/order-food/canteen/list',
      'api/saas/admin/order-food/canteen/add',
      'api/saas/admin/order-food/canteen/info',
      'api/saas/admin/order-food/canteen/edit',
      'api/saas/admin/order-food/canteen/delete',
      'api/saas/admin/order-food/canteen/editStatus',
      'api/saas/admin/order-food/food/add',
      'api/saas/admin/order-food/food-repository/batchLower',
      'api/saas/admin/order-food/advice/listadviceManagement',
      'api/saas/admin/order-food/nutrition/material/list',
      'api/saas/admin/order-food/nutrition/material/add',
      'api/saas/admin/order-food/nutrition/material/edit',
      'api/saas/admin/order-food/nutrition/category/add',
      'api/saas/admin/order-food/nutrition/element/add',
      'api/saas/admin/order-food/nutrition/element/edit',
      'api/saas/admin/order-food/hospital/list',
      'tableCode',
      'api/saas/admin/order-food/device/list',
      'api/saas/admin/order-food/device/add',
      'api/saas/admin/order-food/device/edit',
      'api/saas/admin/order-food/device/switch',
      'api/saas/admin/order-food/device/switch1',
      'api/saas/admin/order-food/device/del',
      'api/saas/admin/order-food/food-Inquire',
      'api/saas/admin/order-food/delivery/address/list',
      'api/saas/admin/order-food/food-Inquire',
      'api/saas/admin/order-food/delivery/address/store',
      'api/saas/admin/order-food/food-repositoryImport',
      'api/saas/admin/order-food/delivery/address/edit',
      'api/saas/admin/order-food/delivery/address/delete',
      'api/saas/admin/order-food/delivery/address/updateDepartment',
      'api/saas/admin/order-food/food-Enable',
      'api/saas/admin/order-food/food-Disable',
      'api/saas/admin/order-food/food-Downloadtemplate',
      'api/saas/admin/order-food/delivery/address/BatchDelete',
      'SelfAccessPointManagement',
      'api/saas/admin/order-food/order_clerk/getList',
      'api/saas/admin/order-food/order_clerk/add',
      'api/saas/admin/order-food/order_clerk/edit',
      'api/saas/admin/order-food/order_clerk/del',
      'api/saas/admin/order-food/placard/list',
      'api/saas/admin/order-food/placard/store',
      'api/saas/admin/order-food/placard/edit',
      'api/saas/admin/order-food/placard/delete',
      'api/saas/admin/order-food/sys/log',
      'marketingTools',
      'api/saas/admin/order-food/set/getSetInfo',
      'account/authorityControl',
      'api/saas/admin/order-food/whiteUser/list',
      'Inquirefjkfjfjfjdjd',
      'Adddevicejjd',
      'BulkimportBulkimport',
      'ExportThetemplate',
      'Jointheblacklist',
      'Removeblacklist',
      'editedit',
      'deletedelete',
      'api/saas/admin/order-food/onCredit/group_list',
      'Adddevicejjdjdj',
      'Inquirefjkfjf',
      'Exportfjfjjfjf',
      'Disablesfjjdj',
      'editediteditedit',
      'ThedetailThedetailThedetail',
      'deletedeletedelete',
      'EnableEnableEnable',
      'api/saas/admin/order-food/onCredit/user_list',
      'AdddeviceAdddevice',
      'InquireInquire',
      'ExportExport',
      'EnableEnable',
      'DisableDisable',
      'editediteditediteditedit',
      'ThedetailThedetail',
      'deletedeletedeletedeletedelete',
      'RestaurantMiddle',
      'Lnquire',
      'ExportExportExport',
      'OrderFoodOrderInfoOrderFoodOrderInfo',
      'makeoutaninvoice',
      'api/saas/admin/order-food/other_order/list',
      'accountManagement',
      'classifiedManagement',
      'api/saas/admin/order-food/adminPage/orderRough',
      'api/saas/admin/order-food/adminPage/departmentOrderCompared',
      'api/saas/admin/order-food/adminPage/orderDescWithTime',
      'api/saas/admin/order-food/adminPage/orderFoodWithTime',
      'api/saas/admin/order-food/order/info',
      'api/saas/admin/order-food/order/export',
      'api/saas/admin/order-food/order/printForStaff',
      'api/saas/admin/order-food/order/printForUser',
      'api/saas/admin/order-food/order/printByDepartment',
      'api/saas/admin/order-food/order/getDepartmentByOrder',
      'api/saas/admin/order-food/food-Signing',
      'api/saas/admin/order-food/food-Review',
      'api/saas/admin/order-food/order/printByBuild',
      'api/saas/admin/order-food/order/printOrder',
      'api/saas/admin/order-food/order/printAllOrder',
      'api/saas/admin/order-food/order/printBySelfDelivery',
      'api/saas/admin/order-food/order/refund',
      'api/saas/admin/order-food/order/printOrderFood',
      'api/saas/admin/order-food/order/printByBuild_tl',
      'api/saas/admin/oreder-food/printingofward',
      'api/saas/admin/order-food/order/printPatientListForHN',
      'api/saas/admin/order-food/order/printFoodsByDepartment',
      'api/saas/admin/order-food/food-repository/getImageFilePicList',
      'api/saas/admin/order-food/food-repository/listImageFile',
      'api/saas/admin/order-food/food-repository/coverImageFood',
      'api/saas/admin/order-food/food-repository/importLogList',
      'api/saas/admin/order-food/food-repository/addImageFile',
      'api/saas/admin/order-food/food-repository/editImageFile',
      'api/saas/admin/order-food/food-repository/delImageFile',
      'api/saas/admin/order-food/food-repository/delImageFilePic',
      'api/saas/admin/order-food/order/getPrintLog',
      'xxx',
      'hospital_catering:api/saas/admin/order-food/order_evaluate/getList',
      'hospital_catering:api/saas/admin/order-food/order/list',
      'http:/fine.report.goliveplus.cn:38888/socket.io',
      'hospital_catering:api/saas/admin/order-food/finance/getBusinessStatementExcel',
      'a/b',
      'hospital_catering:api/saas/admin/order-food/food-repository/list',
      'hospital_catering:api/saas/admin/order-food/food-repository/add',
      'hospital_catering:api/saas/admin/order-food/food-repository/batchUpper',
      'hospital_catering:api/saas/admin/order-food/food-repository/batchLower2',
      'hospital_catering:api/saas/admin/order-food/food-repository/edit',
      'hospital_catering:api/saas/admin/order-food/food-repository/info',
      'hospital_catering:api/saas/admin/order-food/food-repository/delete',
      'hospital_catering:api/saas/admin/order-food/food-repository/import',
      'hospital_catering:api/saas/admin/order-food/public/ossUpload',
      'hospital_catering:api/saas/admin/order-food/food-repository/export_template',
      'hospital_catering:api/saas/admin/order-food/advice/listadviceManagement',
      'hospital_catering:api/saas/admin/order-food/canteen/list',
      'hospital_catering:api/saas/admin/order-food/canteen/add',
      'hospital_catering:api/saas/admin/order-food/canteen/info',
      'hospital_catering:api/saas/admin/order-food/canteen/edit',
      'hospital_catering:api/saas/admin/order-food/canteen/delete',
      'hospital_catering:api/saas/admin/order-food/canteen/editStatus',
      'hospital_catering:api/saas/admin/order-food/food/add',
      'hospital_catering:api/saas/admin/order-food/food-repository/batchLower',
      'hospital_catering:api/saas/admin/order-food/nutrition/material/list',
      'accountManagement2',
      'classifiedManagement2',
      'hospital_catering:api/saas/admin/order-food/hospital/list',
      'tableCode2',
      'hospital_catering:api/saas/admin/order-food/device/list',
      'hospital_catering:api/api/saas/admin/order-food/device/add',
      'hospital_catering:api/api/saas/admin/order-food/device/edit',
      'hospital_catering:api/api/saas/admin/order-food/device/switch',
      'hospital_catering:api/api/saas/admin/order-food/device/switch1',
      'hospital_catering:api/api/saas/admin/order-food/device/del',
      'hospital_catering:api/api/saas/admin/order-food/food-Inquire',
      'hospital_catering:api/saas/admin/order-food/delivery/address/list',
      'hospital_catering:api/saas/admin/order-food/food-Inquire',
      'hospital_catering:api/saas/admin/order-food/delivery/address/store',
      'hospital_catering:api/saas/admin/order-food/food-repositoryImport',
      'hospital_catering:api/saas/admin/order-food/delivery/address/edit',
      'hospital_catering:api/saas/admin/order-food/delivery/address/delete',
      'hospital_catering:api/saas/admin/order-food/delivery/address/updateDepartment',
      'hospital_catering:api/saas/admin/order-food/food-Enable',
      'hospital_catering:api/saas/admin/order-food/food-Disable',
      'hospital_catering:api/saas/admin/order-food/food-Downloadtemplate',
      'hospital_catering:api/saas/admin/order-food/delivery/address/his/sync',
      'SelfAccessPointManagement2',
      'hospital_catering:api/saas/admin/order-food/order_clerk/getList',
      'hospital_catering:api/saas/admin/order-food/order_clerk/add',
      'hospital_catering:api/saas/admin/order-food/order_clerk/edit',
      'hospital_catering:api/saas/admin/order-food/order_clerk/del',
      'hospital_catering:api/saas/admin/order-food/placard/list',
      'hospital_catering:api/saas/admin/order-food/sys/log',
      'a/a/a2',
      'hospital_catering:api/saas/admin/order-food/whiteUser/list',
      'hospital_catering:api/saas/admin/order-food/adminPage/orderRough',
      'hospital_catering:api/saas/admin/order-food/adminPage/departmentOrderCompared',
      'hospital_catering:api/saas/admin/order-food/adminPage/orderDescWithTime',
      'hospital_catering:api/saas/admin/order-food/adminPage/orderFoodWithTime',
      'hospital_catering:api/saas/admin/order-food/order/info',
      'hospital_catering:api/saas/admin/order-food/order/export',
      'api/saas/admin/order-food/order/printForDistByXinAn',
      'api/saas/admin/order-food/order/printForOrderFoodByXinAn',
      'api/saas/admin/order-food/order/printForUserNumByXinAn',
      'hospital_catering:api/saas/admin/order-food/order/printByDepartment',
      'hospital_catering:api/saas/admin/order-food/order/printForStaff',
      'hospital_catering:api/saas/admin/order-food/order/printForUser',
      'hospital_catering:api/saas/admin/order-food/order/getDepartmentByOrder',
      'hospital_catering:api/saas/admin/order-food/order/printOrder',
      'order/list',
      'refund/list',
      'statistics/Terminaltransaction',
      'statistics/download',
      'statistics/networkTransactions',
      'statistics/regionalTrade',
      'statistics/mealNumber',
      'term/list',
      'net/list',
      'area/list',
      'rate/list',
      'posSetting/list',
      'basicSetting/list',
      'order/detail',
      'order/download',
      'saas_pos/refund/unifiedRefund',
      'refund/detail',
      'refund/download',
      'term/insert',
      'term/update',
      'term/delete',
      'term/import',
      'rate/insert',
      'rate/batch/insert',
      'trem/payment',
      'net/insert',
      'net/update',
      'net/delete',
      'area/insert',
      'area/update',
      'area/delete',
      'report/report/homePage',
      'CardBusinessManagement',
      'pay/subsidy/query/page',
      'Card/saas/Consolemanagement',
      'report/charge/order',
      'report/pay/order',
      'report/refund/deductionRecord',
      'report/refund/order',
      'QcardPay/AccountRecords/TransferRecords',
      'report/card/order',
      'report/withdraw/order',
      'report/cancel/order',
      'report/yearCheck/order',
      'report/open',
      'report/cosume/transaction',
      'report/cosume/transactionByday',
      'report/cosume/Operatorreport',
      'report/consume/merch',
      'report/accountCount',
      'report/parkCount',
      'QcardPay/FinancialStatistics/accountTransactionStatement',
      'QcardPay/FinancialStatistics/DailyRechargeReport',
      'manager/sys/getDiscount',
      'manager/sys/getDeviceByLikedName',
      'manager/department/set/departmentName',
      'account/merch/create',
      'manager/sys/create/park',
      'manager/sys/identity/findPage',
      'manager/sys/NetworkManagement',
      'interface',
      'account/account/getAccountDetail',
      'account/user/createUserAuth',
      'account/card/add',
      'account/card/reissue',
      'account/card/replace',
      'pay/subsidy/alone',
      'pay/pay/recharge/branch',
      'account/card/reportLose',
      'account/card/relieveLose',
      'account/account/block',
      'account/account/unblock',
      'account/account/cancel',
      'pay/pay/withdraw',
      'account/card/return',
      'account/card/yearCheck',
      'pay/pay/unRecharge',
      'account/selectConsole',
      'ceshi',
    ],
  },
};
